export const ACTIONS = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  SET_BASKET_QUANTITY: "SET_BASKET_QUANTITY",
  EMPTY_BASKET: "EMPTY_BASKET",
  SET_USER: "SET_USER",
  SET_SEARCH: "SET_SEARCH",
};
